# Generated by Django 5.0.3 on 2024-04-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_blog_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='update',
            new_name='updated',
        ),
    ]
