# Generated by Django 5.0.3 on 2024-04-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_update_blog_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='update',
            new_name='updated',
        ),
    ]
