# Generated by Django 5.0.3 on 2024-07-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_update_topic_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-id']},
        ),
    ]
